model = "gpt-5.4"
model_reasoning_effort = "high"

[notice.model_migrations]
"gpt-5.3-codex" = "gpt-5.4"

[plugins."coderabbit@openai-curated"]
enabled = true

[projects."/Users/markhesketh/Code/markahesketh/dotfiles"]
trust_level = "trusted"

[projects."/Users/markhesketh/Code/markahesketh/thevamoose.com"]
trust_level = "trusted"
